import type { Locale } from "@/lib/i18n"

/**
 * Тексты кабинета. Отдельно от общего словаря сайта: кабинет закрыт от
 * поиска, живёт своим набором понятий (лимит, ключ, приглашения) и растёт
 * быстрее витрины — держать это в общем файле значит листать его целиком
 * ради одной подписи.
 */
export const ACCOUNT_TEXTS = {
  ru: {
    nav: {
      library: "Библиотека",
      account: "Аккаунт",
      sections: "Разделы",
      overview: "Обзор",
      favorites: "Избранное",
      history: "История",
      billing: "Тариф и оплата",
      connect: "Подключение к проекту",
      referrals: "Рефералы",
      profile: "Профиль и безопасность",
      support: "Поддержка",
      payments: "Оплата",
      catalog: "Открыть каталог",
    },
    plan: { free: "Бесплатный", pro: "Pro", bonus: "Бонусный Pro" },
    payments: {
      title: "Оплата",
      lead: "История платежей и чеки. Чек формируется в «Мой налог» после оплаты и появляется здесь ссылкой.",
      receipt: "Чек",
      receiptSoon: "Чек готовится",
      empty: "Платежей пока не было.",
      more: "Показать ещё",
    },
    overview: {
      title: "Моя библиотека",
      lead: "Вернитесь к выбранному дизайну.",
      resume: "Продолжить работу",
      resumeEmpty: "Здесь появится компонент, с которым вы работали.",
      open: "Открыть",
      taken: "Взят",
      savedTitle: "Избранное",
      savedAll: "Открыть всё",
      savedEmpty: "Сердце на карточке каталога откладывает компонент сюда.",
      recentTitle: "Недавно брали",
      recentAll: "Вся история",
      recentEmpty: "Первый скопированный компонент появится здесь.",
      startTitle: "С чего начать",
      startSteps: [
        "Выберите компонент в каталоге",
        "Сохраните его в избранное",
        "Отдайте ссылку ИИ-агенту",
      ],
      startAction: "Выбрать первый компонент",
      limitLeft: (left: number, total: number) =>
        `${left} из ${total} доступно`,
      limitResets: (date: string) => `Обновится ${date}`,
      limitNote:
        "Считаются разные компоненты: повторное копирование того же самого лимит не занимает.",
      proTitle: "Доступ Pro",
      proUntil: (date: string) => `Действует до ${date}`,
      proNote: "Компоненты без ограничений, закрытые — тоже.",
      manage: "Управлять",
      upgrade: "Смотреть тарифы",
      planFree: "Бесплатный тариф",
      planPro: "Тариф Pro",
      noLimit: "Без лимита",
      of: (total: number) => `из ${total}`,
      limitTitle: "Осталось в этом месяце",
      monthTaken: "Взято в этом месяце",
      allTime: "Всего компонентов",
      savedCount: "В избранном",
      daysToReset: "Дней до обновления лимита",
      daysLeft: "Дней доступа",
      activity: "Активность за 30 дней",
      activityNote: "Разные компоненты по дням первого обращения.",
    },
    favorites: {
      title: "Избранное",
      lead: "Отложенные компоненты: список, поиск и фильтр по типу. Превью и код — на странице компонента.",
      count: (n: number) => `Сохранено: ${n}`,
      search: "Поиск по избранному",
      searchPlaceholder: "Название или код…",
      filterAll: "Все",
      empty: "Здесь пока пусто",
      emptyNote:
        "Нажмите сердце на карточке в каталоге — компонент отложится сюда, и его не придётся искать заново.",
      emptyAction: "В каталог",
      nothingFound: "Ничего не нашлось",
      remove: "Убрать",
      removed: "Убрано из избранного",
      undo: "Вернуть",
      copy: "Копировать для ИИ",
      copied: "Скопировано",
      openItem: "Открыть",
      more: "Показать ещё",
    },
    history: {
      title: "История",
      lead: "Компоненты, которые вы брали. Запись появляется при первом обращении к компоненту в месяце — это не счётчик копирований.",
      search: "Поиск по истории",
      searchPlaceholder: "Название или код…",
      allMonths: "Все месяцы",
      empty: "Записей пока нет. Первый скопированный компонент появится здесь.",
      nothingFound: "Ничего не нашлось",
      apply: "Показать",
    },
    billing: {
      title: "Тариф и оплата",
      currentPlan: "Текущий тариф",
      freeTitle: "Бесплатный",
      freeNote: (limit: number) =>
        `${limit} компонентов в месяц, избранное и история. Оплата не нужна.`,
      proNote: (date: string) =>
        `Компоненты без ограничений, закрытые — тоже. Оплата разовая, автосписаний нет: доступ до ${date}, потом тариф станет бесплатным, оплатить снова можно в любой момент.`,
      until: (date: string) => `Доступ до ${date}`,
      bonusNote: "Бонусные дни. Когда они закончатся, тариф станет бесплатным.",
      expiredTitle: "Срок доступа закончился",
      expiredNote: (date: string) =>
        `Доступ Pro закончился ${date}. Бесплатный тариф продолжает работать.`,
      extend: "Продлить доступ",
      periodTitle: "Оплаченный период",
      periodStarted: "Начало",
      periodEnds: "Окончание",
      today: "Сегодня",
      plan: "Тариф",
      price: "Цена",
      accessUntil: "Доступ до",
      billingMode: "Оплата",
      oneOff: "Разовая, без автосписаний",
      paidTotal: "Оплачено всего",
      paymentsCount: (n: number) =>
        `${n} платеж${n % 10 === 1 && n % 100 !== 11 ? "" : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? "а" : "ей"}`,
      columnDate: "Дата",
      columnAmount: "Сумма",
      columnStatus: "Статус",
      columnReceipt: "Чек",
      choosePlan: "Смотреть тарифы",
      payAgain: "Оплатить снова",
      pendingTitle: "Ждём подтверждения оплаты",
      pendingNote:
        "ЮKassa подтверждает платёж в течение нескольких минут. Обновите страницу — статус появится здесь.",
      refresh: "Обновить",
      payments: "История оплат и чеки",
      paymentsNote: "Чек появляется здесь после формирования в «Мой налог».",
      paymentsEmpty: "Платежей пока не было.",
      status: {
        succeeded: "Оплачен",
        pending: "Ожидает",
        canceled: "Отменён",
        refunded: "Возвращён",
        unknown: "Неизвестен",
      },
      more: "Показать ещё",
    },
    connect: {
      title: "Подключение к проекту",
      lead: "Три шага, чтобы агент ставил компоненты прямо в ваш проект.",
      step1: "Возьмите команду установки",
      step1Free:
        "Бесплатные компоненты ставятся без ключа: команда есть на странице каждого компонента.",
      step2: "Настройте проект",
      step2Note:
        "Команда работает в любом проекте с shadcn/ui. Файл ляжет в ваш репозиторий и останется вашим.",
      step3: "Выполните установку",
      step3Note:
        "Агент выполнит команду сам, если отдать ему ссылку компонента из каталога.",
      keyTitle: "Ключ установки",
      keyLead:
        "Ключ нужен, чтобы shadcn CLI мог поставить закрытые компоненты: он ходит по адресу и не знает про вашу сессию в браузере.",
      keyFree:
        "Ключ выдаётся вместе с подпиской. Бесплатные компоненты ставятся и без него.",
      create: "Создать ключ",
      creating: "Создаём…",
      replace: "Заменить ключ",
      replaceWarning:
        "Новый ключ погасит действующий: в проектах, где остался старый, установка перестанет работать.",
      confirmReplace: "Да, заменить",
      cancel: "Отмена",
      freshTitle: "Ключ создан. Он показывается один раз",
      freshNote:
        "Скопируйте и сохраните его в переменных окружения проекта. Мы храним только отпечаток.",
      copy: "Копировать ключ",
      copied: "Скопировано",
      revoke: "Отозвать",
      revoking: "Отзываем…",
      confirmRevoke: "Отозвать ключ? Установка по нему перестанет работать.",
      created: (date: string) => `Создан ${date}`,
      lastUsed: (date: string) => `Использован ${date}`,
      neverUsed: "Ещё не использовался",
      active: "Действует",
      revoked: "Отозван",
      noKeys: "Ключей пока нет.",
      failed: "Не получилось. Действующий ключ сохранён, попробуйте ещё раз.",
      upgrade: "Смотреть тарифы",
    },
    referrals: {
      title: "Рефералы",
      lead: "Ваша партнёрская ссылка. Кто зарегистрируется по ней, закрепляется за вами; оплатившие отмечены в списке.",
      copy: "Скопировать",
      copied: "Скопировано",
      clicks: "Переходов",
      signedUp: "Зарегистрировались",
      paid: "Оплатили",
      listTitle: "Мои рефералы",
      listEmpty: "Пока никто не зарегистрировался по вашей ссылке.",
      paidLabel: "Оплатил",
      notPaid: "Не оплачивал",
      more: "Показать ещё",
      conversion: "Конверсия в оплату",
      period: { 30: "30 дней", 90: "90 дней" },
      versus: "к прошлому периоду",
      dynamics: "Динамика",
      dynamicsNote: "Переходы по ссылке и регистрации по дням.",
      funnelTitle: "Воронка",
      funnelNote: "От перехода до первой оплаты за выбранный период.",
      linkTitle: "Партнёрская ссылка",
      code: "Код",
      promoTitle: "Промокод",
      promoLead:
        "Ваш ник как промокод: зритель вводит его на тарифах и платит первый раз со скидкой, платёж закрепляется за вами.",
      promoNone: "Промокод пока не назначен — напишите нам в поддержку.",
      promoDiscount: (percent: number) => `−${percent} % на первый платёж`,
      promoPayments: "Оплат по промокоду",
      promoRevenue: "на сумму",
      columnPerson: "Человек",
      columnStatus: "Статус",
      columnDate: "Регистрация",
      allTime: "за всё время",
      howTitle: "Как это считается",
      how: [
        "Переход по ссылке запоминается на 60 дней — регистрироваться сразу необязательно.",
        "Человек закрепляется за вами в момент регистрации, навсегда.",
        "«Оплатил» — у него был хотя бы один успешный платёж за подписку.",
      ],
    },
    profile: {
      title: "Профиль и безопасность",
      nameTitle: "Имя",
      nameNote: "Так вас зовут в кабинете и в письмах.",
      nameLabel: "Имя",
      save: "Сохранить",
      saving: "Сохраняем…",
      saved: "Сохранено",
      emailTitle: "Почта",
      verified: "Подтверждена",
      unverified: "Не подтверждена",
      verify: "Отправить письмо ещё раз",
      localeTitle: "Язык писем",
      localeNote: "На этом языке приходят письма о подписке и восстановлении.",
      passwordTitle: "Смена пароля",
      passwordNote:
        "Вход на других устройствах закроется — это способ вернуть себе аккаунт, если пароль куда-то утёк. Текущая вкладка останется открытой.",
      current: "Текущий пароль",
      next: "Новый пароль",
      hint: "Не короче 10 символов",
      change: "Сменить пароль",
      changing: "Меняем…",
      changed: "Пароль обновлён",
      wrongPassword: "Текущий пароль не подошёл",
      tooMany: "Слишком много попыток. Попробуйте через несколько минут.",
      failed: "Не получилось. Попробуйте ещё раз.",
      devicesTitle: "Устройства",
      devicesNote:
        "Активные входы в аккаунт. Точное место по IP не определяем — показываем только браузер и время.",
      thisDevice: "Это устройство",
      lastSeen: (date: string) => `Активность ${date}`,
      signOutOthers: "Завершить остальные сессии",
      signingOut: "Завершаем…",
      othersSignedOut: "Остальные сессии завершены",
      noOthers: "Других активных сессий нет.",
    },
    common: {
      back: "Назад",
      loading: "Загружаем…",
      errorTitle: "Не удалось загрузить раздел",
      errorNote:
        "Обычно помогает повторить попытку: данные читаются из базы, и это могла быть временная заминка.",
      retry: "Повторить",
    },
  },
  en: {
    nav: {
      library: "Library",
      account: "Account",
      sections: "Sections",
      overview: "Overview",
      favorites: "Favourites",
      history: "History",
      billing: "Plan and billing",
      connect: "Connect your project",
      referrals: "Referrals",
      profile: "Profile and security",
      support: "Support",
      payments: "Payments",
      catalog: "Open the catalogue",
    },
    plan: { free: "Free", pro: "Pro", bonus: "Bonus Pro" },
    payments: {
      title: "Payments",
      lead: "Payment history and receipts. A receipt is issued through the tax service after payment and appears here as a link.",
      receipt: "Receipt",
      receiptSoon: "Receipt pending",
      empty: "No payments yet.",
      more: "Show more",
    },
    overview: {
      title: "My library",
      lead: "Pick up where you left off.",
      resume: "Continue working",
      resumeEmpty: "The component you worked with will show up here.",
      open: "Open",
      taken: "Taken",
      savedTitle: "Favourites",
      savedAll: "Open all",
      savedEmpty: "The heart on a catalogue card saves a component here.",
      recentTitle: "Recently taken",
      recentAll: "Full history",
      recentEmpty: "The first component you copy will show up here.",
      startTitle: "How to start",
      startSteps: [
        "Pick a component in the catalogue",
        "Save it to favourites",
        "Hand the link to your AI agent",
      ],
      startAction: "Pick your first component",
      limitLeft: (left: number, total: number) => `${left} of ${total} left`,
      limitResets: (date: string) => `Resets on ${date}`,
      limitNote:
        "Distinct components count: copying the same one again does not use the limit.",
      proTitle: "Pro access",
      proUntil: (date: string) => `Active until ${date}`,
      proNote: "Components without limits, closed ones included.",
      manage: "Manage",
      upgrade: "See plans",
      planFree: "Free plan",
      planPro: "Pro plan",
      noLimit: "No limit",
      of: (total: number) => `of ${total}`,
      limitTitle: "Left this month",
      monthTaken: "Taken this month",
      allTime: "Components overall",
      savedCount: "In favourites",
      daysToReset: "Days until the limit resets",
      daysLeft: "Days of access",
      activity: "Activity, last 30 days",
      activityNote:
        "Distinct components by the day you first reached for them.",
    },
    favorites: {
      title: "Favourites",
      lead: "Saved components: a list with search and a type filter. Preview and code live on the component page.",
      count: (n: number) => `Saved: ${n}`,
      search: "Search favourites",
      searchPlaceholder: "Name or code…",
      filterAll: "All",
      empty: "Nothing here yet",
      emptyNote:
        "Press the heart on a catalogue card — the component lands here and you will not have to look for it again.",
      emptyAction: "To the catalogue",
      nothingFound: "Nothing found",
      remove: "Remove",
      removed: "Removed from favourites",
      undo: "Undo",
      copy: "Copy for AI",
      copied: "Copied",
      openItem: "Open",
      more: "Show more",
    },
    history: {
      title: "History",
      lead: "Components you have taken. A row appears the first time you reach for a component in a month — this is not a copy counter.",
      search: "Search history",
      searchPlaceholder: "Name or code…",
      allMonths: "All months",
      empty: "No records yet. The first component you copy will show up here.",
      nothingFound: "Nothing found",
      apply: "Show",
    },
    billing: {
      title: "Plan and billing",
      currentPlan: "Current plan",
      freeTitle: "Free",
      freeNote: (limit: number) =>
        `${limit} components a month, favourites and history. No payment needed.`,
      proNote: (date: string) =>
        `Components without limits, closed ones included. One-off payment, no auto-charges: access until ${date}, then the plan becomes free and you can pay again any time.`,
      until: (date: string) => `Access until ${date}`,
      bonusNote: "Bonus days. When they run out, the plan becomes free.",
      expiredTitle: "Access period ended",
      expiredNote: (date: string) =>
        `Pro access ended on ${date}. The free plan keeps working.`,
      extend: "Extend access",
      periodTitle: "Paid period",
      periodStarted: "Started",
      periodEnds: "Ends",
      today: "Today",
      plan: "Plan",
      price: "Price",
      accessUntil: "Access until",
      billingMode: "Billing",
      oneOff: "One-off, no auto-charges",
      paidTotal: "Paid in total",
      paymentsCount: (n: number) => `${n} payment${n === 1 ? "" : "s"}`,
      columnDate: "Date",
      columnAmount: "Amount",
      columnStatus: "Status",
      columnReceipt: "Receipt",
      choosePlan: "See plans",
      payAgain: "Pay again",
      pendingTitle: "Waiting for the payment to clear",
      pendingNote:
        "YooKassa confirms a payment within a few minutes. Refresh the page — the status will show up here.",
      refresh: "Refresh",
      payments: "Payment history and receipts",
      paymentsNote:
        "A receipt appears here once it is issued through the tax service.",
      paymentsEmpty: "No payments yet.",
      status: {
        succeeded: "Paid",
        pending: "Pending",
        canceled: "Cancelled",
        refunded: "Refunded",
        unknown: "Unknown",
      },
      more: "Show more",
    },
    connect: {
      title: "Connect your project",
      lead: "Three steps and your agent installs components straight into the project.",
      step1: "Take the install command",
      step1Free:
        "Free components install without a key: the command sits on every component page.",
      step2: "Set up the project",
      step2Note:
        "The command works in any project with shadcn/ui. The file lands in your repository and stays yours.",
      step3: "Run the install",
      step3Note:
        "Your agent runs the command itself once you hand it a component link from the catalogue.",
      keyTitle: "Install key",
      keyLead:
        "The key lets the shadcn CLI install closed components: it goes by URL and knows nothing about your browser session.",
      keyFree:
        "The key comes with a subscription. Free components install without it.",
      create: "Create a key",
      creating: "Creating…",
      replace: "Replace the key",
      replaceWarning:
        "A new key retires the current one: installs will stop working in projects that still use the old key.",
      confirmReplace: "Yes, replace",
      cancel: "Cancel",
      freshTitle: "The key is ready. It is shown once",
      freshNote:
        "Copy it into your project environment variables. We keep only a fingerprint.",
      copy: "Copy the key",
      copied: "Copied",
      revoke: "Revoke",
      revoking: "Revoking…",
      confirmRevoke: "Revoke the key? Installs using it will stop working.",
      created: (date: string) => `Created ${date}`,
      lastUsed: (date: string) => `Used ${date}`,
      neverUsed: "Never used",
      active: "Active",
      revoked: "Revoked",
      noKeys: "No keys yet.",
      failed: "That did not work. The current key is intact, please try again.",
      upgrade: "See plans",
    },
    referrals: {
      title: "Referrals",
      lead: "Your partner link. Whoever signs up through it is attributed to you; paying members are marked in the list.",
      copy: "Copy",
      copied: "Copied",
      clicks: "Visits",
      signedUp: "Signed up",
      paid: "Paid",
      listTitle: "My referrals",
      listEmpty: "Nobody has signed up through your link yet.",
      paidLabel: "Paid",
      notPaid: "Not paid",
      more: "Show more",
      conversion: "Paid conversion",
      period: { 30: "30 days", 90: "90 days" },
      versus: "vs previous period",
      dynamics: "Dynamics",
      dynamicsNote: "Link visits and signups by day.",
      funnelTitle: "Funnel",
      funnelNote: "From a visit to the first payment within the period.",
      linkTitle: "Partner link",
      code: "Code",
      promoTitle: "Promo code",
      promoLead:
        "Your handle as a promo code: a viewer enters it on the pricing page, pays the first time with a discount, and the payment is attributed to you.",
      promoNone: "No promo code assigned yet — contact support.",
      promoDiscount: (percent: number) => `−${percent} % off the first payment`,
      promoPayments: "Payments with the code",
      promoRevenue: "totalling",
      columnPerson: "Person",
      columnStatus: "Status",
      columnDate: "Signed up",
      allTime: "all time",
      howTitle: "How it adds up",
      how: [
        "A visit through the link is remembered for 60 days — signing up right away is not required.",
        "A person is attributed to you at signup, permanently.",
        "“Paid” means at least one successful subscription payment.",
      ],
    },
    profile: {
      title: "Profile and security",
      nameTitle: "Name",
      nameNote: "This is how the account and the letters address you.",
      nameLabel: "Name",
      save: "Save",
      saving: "Saving…",
      saved: "Saved",
      emailTitle: "Email",
      verified: "Confirmed",
      unverified: "Not confirmed",
      verify: "Send the letter again",
      localeTitle: "Language of letters",
      localeNote: "Subscription and password letters arrive in this language.",
      passwordTitle: "Change password",
      passwordNote:
        "Other devices will be signed out — that is how you take the account back if the password leaked. This tab stays open.",
      current: "Current password",
      next: "New password",
      hint: "At least 10 characters",
      change: "Change password",
      changing: "Changing…",
      changed: "Password updated",
      wrongPassword: "The current password did not match",
      tooMany: "Too many attempts. Try again in a few minutes.",
      failed: "That did not work. Please try again.",
      devicesTitle: "Devices",
      devicesNote:
        "Active sign-ins. We do not guess the exact location from an IP — only the browser and the time.",
      thisDevice: "This device",
      lastSeen: (date: string) => `Active ${date}`,
      signOutOthers: "Sign out other sessions",
      signingOut: "Signing out…",
      othersSignedOut: "Other sessions are signed out",
      noOthers: "No other active sessions.",
    },
    common: {
      back: "Back",
      loading: "Loading…",
      errorTitle: "Could not load this section",
      errorNote:
        "Trying again usually helps: the data comes from the database and this may have been a hiccup.",
      retry: "Try again",
    },
  },
} as const satisfies Record<Locale, unknown>

export type AccountText = (typeof ACCOUNT_TEXTS)["ru"]
