export const adminHtml = `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VibeUI Agents</title><style>
:root{color-scheme:dark;--bg:#09090b;--panel:#151518;--line:#2b2b30;--text:#f5f5f5;--muted:#a1a1aa;--accent:#a78bfa;--danger:#ef4444}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.5 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:28px}
h1{margin:0;font-size:28px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px}.muted{color:var(--muted)}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin:24px 0}.card,.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px}.value{font-size:28px;font-weight:700}
.controls{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}button{border:1px solid var(--line);background:#25252a;color:#fff;border-radius:9px;padding:9px 13px;cursor:pointer}button.danger{background:var(--danger);border-color:var(--danger)}button.safe{background:#166534}.small{padding:4px 7px;font-size:12px}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pill{padding:3px 8px;border-radius:99px;background:#27272a}code{color:var(--accent)}
@media(max-width:800px){main{padding:18px}.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.panel{overflow:auto}}
</style></head><body><main>
<div class="top"><div><h1>VibeUI Agents</h1><div class="muted">Контроль автономного привлечения блогеров</div></div><div id="updated" class="muted"></div></div>
<div class="controls"><button data-control="pause">Пауза рассылки</button><button class="safe" data-control="resume">Разрешить рассылку</button><button data-control="pause-partnerships">Пауза партнёров</button><button data-control="pause-payouts">Пауза выплат</button><button class="danger" data-control="stop">Остановить всё</button><button data-control="clear-stop">Только безопасные задачи</button></div>
<div class="cards"><div class="card"><div class="muted">Кандидаты</div><div class="value" id="candidates">—</div></div><div class="card"><div class="muted">В очереди</div><div class="value" id="queued">—</div></div><div class="card"><div class="muted">Ошибки</div><div class="value" id="failed">—</div></div><div class="card"><div class="muted">Управление</div><div id="control">—</div></div></div>
<div class="grid"><section class="panel"><h2>Последние запуски</h2><table><thead><tr><th>Агент</th><th>Статус</th><th>Начало</th></tr></thead><tbody id="runs"></tbody></table></section><section class="panel"><h2>Последние действия</h2><table><thead><tr><th>Действие</th><th>Решение</th><th>Время</th></tr></thead><tbody id="actions"></tbody></table></section></div>
<section class="panel"><h2>Блогеры</h2><table><thead><tr><th>Имя</th><th>Рынок</th><th>Площадка</th><th>Аудитория</th><th>Score</th><th>Статус</th><th></th></tr></thead><tbody id="creators"></tbody></table></section>
<section class="panel"><h2>Сообщения</h2><table><thead><tr><th>Автор</th><th>Тип</th><th>Тема</th><th>Статус</th><th></th></tr></thead><tbody id="messages"></tbody></table></section>
<div class="grid"><section class="panel"><h2>Очередь</h2><table><thead><tr><th>Задача</th><th>Статус</th><th>Попытки</th><th></th></tr></thead><tbody id="jobs"></tbody></table></section><section class="panel"><h2>Уведомления</h2><table><thead><tr><th>Уровень</th><th>Событие</th><th>Время</th></tr></thead><tbody id="notifications"></tbody></table></section></div>
</main><script>
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function refresh(){const r=await fetch('/api/dashboard');if(!r.ok)return;const d=await r.json();
document.querySelector('#candidates').textContent=d.counts.candidates;document.querySelector('#queued').textContent=d.counts.queued;document.querySelector('#failed').textContent=d.counts.failed;
document.querySelector('#control').innerHTML='<span class="pill">'+(d.control.emergency_stop?'STOP':d.control.outreach_paused?'PAUSED':'ACTIVE')+'</span>';
document.querySelector('#runs').innerHTML=d.runs.map(x=>'<tr><td>'+esc(x.agent_name)+'</td><td>'+esc(x.status)+'</td><td>'+esc(new Date(x.started_at).toLocaleString())+'</td></tr>').join('');
document.querySelector('#actions').innerHTML=d.actions.map(x=>'<tr><td>'+esc(x.action)+'</td><td>'+esc(x.decision)+'</td><td>'+esc(new Date(x.created_at).toLocaleString())+'</td></tr>').join('');document.querySelector('#updated').textContent='Обновлено '+new Date().toLocaleTimeString()}
document.querySelector('#creators').innerHTML=d.creators.map(x=>'<tr><td>'+esc(x.display_name)+'</td><td>'+esc(x.market)+'</td><td>'+esc(x.platform)+'</td><td>'+esc(x.followers)+'</td><td>'+esc(x.score)+'</td><td>'+esc(x.status)+'</td><td><button class="small" data-object="do_not_contact" data-id="'+esc(x.id)+'">DNC</button></td></tr>').join('');
document.querySelector('#messages').innerHTML=d.messages.map(x=>'<tr><td>'+esc(x.display_name)+'</td><td>'+esc(x.kind)+'</td><td>'+esc(x.subject)+'</td><td>'+esc(x.status)+'</td><td>'+(x.status==='draft'?'<button class="small safe" data-object="approve_message" data-id="'+esc(x.id)+'">Одобрить</button>':'')+'</td></tr>').join('');
document.querySelector('#jobs').innerHTML=d.jobs.map(x=>'<tr><td>'+esc(x.kind)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.attempts)+'/'+esc(x.max_attempts)+'</td><td>'+(x.status==='queued'?'<button class="small" data-object="cancel_job" data-id="'+esc(x.id)+'">Отмена</button>':x.status==='failed'?'<button class="small" data-object="retry_job" data-id="'+esc(x.id)+'">Retry</button>':'')+'</td></tr>').join('');
document.querySelector('#notifications').innerHTML=d.notifications.map(x=>'<tr><td>'+esc(x.severity)+'</td><td>'+esc(x.title)+'</td><td>'+esc(new Date(x.created_at).toLocaleString())+'</td></tr>').join('');document.querySelector('#updated').textContent='Обновлено '+new Date().toLocaleTimeString();bindActions()}
function bindActions(){document.querySelectorAll('[data-object]').forEach(b=>b.onclick=async()=>{if(!confirm('Подтвердить действие?'))return;await fetch('/api/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:b.dataset.object,id:b.dataset.id})});await refresh()})}
document.querySelectorAll('[data-control]').forEach(b=>b.onclick=async()=>{if((b.dataset.control==='resume'||b.dataset.control==='clear-stop')&&!confirm('Подтвердить изменение защитного режима?'))return;await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:b.dataset.control})});await refresh()});refresh();setInterval(refresh,5000);
</script></body></html>`;
