import {
  AlignLeft,
  AppWindow,
  ArrowDownFromLine,
  ArrowDownToLine,
  ArrowDownUp,
  ArrowLeftToLine,
  ArrowRight,
  ArrowRightToLine,
  ArrowUpFromLine,
  ArrowUpToLine,
  Asterisk,
  Ban,
  Bell,
  Blend,
  Bold,
  Boxes,
  Braces,
  CalendarCheck,
  CalendarClock,
  Captions,
  Check,
  RefreshCw,
  Settings2,
  StickyNote,
  Ticket,
  CircleSlash,
  Fingerprint,
  LogOut,
  Pencil,
  Trash2,
  MousePointerClick,
  AtSign,
  Mail,
  MessageSquare,
  Info,
  Quote,
  ChevronDown,
  ChevronsUp,
  ChevronsUpDown,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleDot,
  CircleUser,
  Clock,
  Coins,
  Columns2,
  Columns3,
  Crosshair,
  Diamond,
  Droplet,
  Ellipsis,
  ExternalLink,
  Eye,
  File,
  FileType,
  Files,
  Folders,
  Gauge,
  Globe,
  Grid2x2,
  HardDrive,
  Hash,
  Heart,
  Highlighter,
  History,
  Hourglass,
  ImageIcon,
  Inbox,
  KeyRound,
  Laptop,
  Layers,
  ListCollapse,
  LayoutGrid,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  LoaderCircle,
  Lock,
  MapPin,
  Maximize2,
  Milestone,
  Minus,
  Moon,
  MoveHorizontal,
  MoveVertical,
  OctagonAlert,
  Package,
  Palette,
  PanelLeft,
  PanelLeftClose,
  Percent,
  PictureInPicture2,
  PieChart,
  Pin,
  Plug,
  Plus,
  Power,
  Proportions,
  Rotate3d,
  RotateCcw,
  Ruler,
  Scan,
  Shapes,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Signal,
  Square,
  SquareDashed,
  SquareStack,
  SquareTerminal,
  Star,
  Sun,
  Sunrise,
  Sunset,
  SwatchBook,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  TrendingUp,
  Triangle,
  Type,
  UserCheck,
  UserPlus,
  Users,
  WholeWord,
  WrapText,
  ZoomIn,
  Flag,
  GitBranch,
  GitCommitVertical,
  IndentIncrease,
  Rows2,
  Rows3,
  Sparkles,
  Tag,
  PaintBucket,
  Timer,
  TriangleAlert,
  CalendarDays,
  CalendarFold,
  CalendarRange,
  Languages,
  Crown,
  Radio,
  Scissors,
  Server,
  CreditCard,
  Medal,
  Banknote,
  Repeat,
  Search,
  Minimize2,
  Signature,
  LogIn,
  Keyboard,
  type LucideIcon,
} from "lucide-react"

import type { ControlValue, ItemControl } from "@/registry/meta"

/**
 * База значков для быстрых настроек на карточке витрины.
 *
 * По карточке настройка крутится одной кнопкой, поэтому значок должен читаться
 * без подписи. Пропов в библиотеке под тысячу, и словаря «на каждое имя» тут
 * быть не может: база собрана по смыслу — повторяющиеся роли, которые
 * встречаются у разных компонентов. Незнакомый проп получает значок своего
 * типа, а не выпадает из карточки.
 */
const BY_PROP: Record<string, LucideIcon> = {
  accent: Palette,
  active: ListFilter,
  accentDark: Moon,
  accentForeground: Type,
  accentLight: Sun,
  activeLabel: MapPin,
  align: AlignLeft,
  average: Star,
  arrow: ArrowRight,
  attempts: RotateCcw,
  autoRetry: RotateCcw,
  checkedSize: Maximize2,
  columns: Columns3,
  cap: Ruler,
  compactAt: Ruler,
  cooldown: Timer,
  corner: PictureInPicture2,
  cover: ImageIcon,
  count: Hash,
  cartCount: ShoppingCart,
  current: MapPin,
  currentKind: Shapes,
  currentLocale: Languages,
  currentVersion: GitBranch,
  currentWeek: CalendarCheck,
  notifications: Bell,
  defaultAlign: AlignLeft,
  defaultChecked: Power,
  defaultChoice: CircleDot,
  defaultCode: Flag,
  defaultCollapsed: PanelLeftClose,
  defaultColumn: Columns2,
  defaultCurrency: Coins,
  defaultFolders: Folders,
  defaultId: CircleCheck,
  defaultLeft: PanelLeft,
  defaultList: Inbox,
  defaultMiddle: Columns3,
  defaultRatio: Proportions,
  defaultRow: Rows2,
  defaultSize: Columns2,
  defaultMonth: CalendarRange,
  defaultPressed: Power,
  defaultOpen: ListCollapse,
  defaultPage: File,
  defaultPerPage: Rows3,
  defaultShown: Eye,
  defaultStatus: LoaderCircle,
  defaultTo: ArrowRightToLine,
  defaultValue: CircleCheck,
  defaultView: LayoutGrid,
  defaultYear: CalendarFold,
  danger: OctagonAlert,
  delay: Clock,
  delta: Percent,
  decimals: Ruler,
  dense: Layers,
  density: Layers,
  destructive: OctagonAlert,
  disabled: Ban,
  discount: Percent,
  divider: Minus,
  duration: Clock,
  background: PaintBucket,
  baseSize: Users,
  batch: Boxes,
  badge: Tag,
  budgetUsed: Gauge,
  busy: LoaderCircle,
  channel: GitBranch,
  dayNorm: Timer,
  days: CalendarDays,
  dot: Circle,
  goodDirection: TrendingUp,
  highlight: Highlighter,
  level: Signal,
  taxRate: Percent,
  placement: Crosshair,
  platform: Laptop,
  show: Eye,
  stage: Milestone,
  elapsed: Hourglass,
  elevation: SquareStack,
  errorFrom: ArrowUpToLine,
  errorTo: ArrowDownToLine,
  exitCode: SquareTerminal,
  expected: Ruler,
  glow: Sparkles,
  gradient: Sparkles,
  fadeOut: ArrowDownToLine,
  isometric: Rotate3d,
  guide: IndentIncrease,
  exclusive: CircleDot,
  from: ArrowLeftToLine,
  to: ArrowRightToLine,
  gap: Columns2,
  height: MoveVertical,
  hue: SwatchBook,
  extension: FileType,
  icon: Shapes,
  index: Hash,
  ink: Droplet,
  inset: SquareDashed,
  interval: Clock,
  invert: Blend,
  keep: WholeWord,
  labelWidth: Columns2,
  languageColor: Braces,
  layout: LayoutGrid,
  length: Ruler,
  limit: Ruler,
  loading: LoaderCircle,
  love: Heart,
  lowAt: TriangleAlert,
  locale: Languages,
  markPeak: Target,
  marker: Triangle,
  max: Rows3,
  maxSelected: ListChecks,
  maxSizeMb: HardDrive,
  maxVisible: Ellipsis,
  minLength: Ruler,
  minTile: Ruler,
  minWidth: Ruler,
  month: CalendarRange,
  more: Ellipsis,
  normHours: Clock,
  numbered: ListOrdered,
  open: ChevronsUpDown,
  orientation: ArrowDownUp,
  overdue: CalendarClock,
  overlap: Layers,
  page: File,
  pageSize: Rows3,
  pendingDuration: Timer,
  percent: Percent,
  perPage: Rows3,
  pin: Pin,
  placeholderWidth: Ruler,
  price: Coins,
  progress: Gauge,
  prompt: Terminal,
  radius: Proportions,
  ratio: Proportions,
  rail: GitCommitVertical,
  recentLimit: History,
  required: Asterisk,
  resetDelay: Timer,
  ring: Circle,
  role: UserCheck,
  src: ImageIcon,
  name: CircleUser,
  hint: Info,
  meta: Clock,
  bio: Quote,
  email: Mail,
  seed: Fingerprint,
  team: Users,
  moreText: Ellipsis,
  typingText: MessageSquare,
  seenText: History,
  tag: Tag,
  message: MessageSquare,
  actionLabel: MousePointerClick,
  dismissLabel: CircleSlash,
  version: GitBranch,
  acceptLabel: ThumbsUp,
  rejectLabel: Ban,
  settingsLabel: Settings2,
  environment: Server,
  note: StickyNote,
  detail: Info,
  retryLabel: RefreshCw,
  code: Ticket,
  person: CircleUser,
  operator: UserCheck,
  exitLabel: LogOut,
  date: CalendarDays,
  label: Captions,
  title: Type,
  action: MousePointerClick,
  handle: AtSign,
  when: Clock,
  since: CalendarDays,
  output: Ruler,
  signOutLabel: LogOut,
  editLabel: Pencil,
  removeLabel: Trash2,
  saveLabel: Check,
  resetLabel: RotateCcw,
  rowCount: Rows3,
  rows: List,
  saving: Percent,
  scheme: Link,
  seatsTotal: Users,
  seatsUsed: UserCheck,
  seconds: Timer,
  segments: CircleDashed,
  selected: CircleDot,
  separator: Plus,
  shape: Diamond,
  showAverage: Sigma,
  star: Star,
  showLabels: Captions,
  showStats: Sigma,
  showValues: Hash,
  siblings: Ellipsis,
  side: Columns2,
  single: CircleDot,
  size: Maximize2,
  slaDays: CalendarClock,
  soonInDays: Hourglass,
  speed: Gauge,
  stepMinutes: Timer,
  start: ListOrdered,
  startCollapsed: ListCollapse,
  status: CircleDot,
  state: CircleDot,
  step: Hash,
  stripe: Flag,
  target: Crosshair,
  tilt: Rotate3d,
  today: CalendarCheck,
  tone: Palette,
  total: Files,
  trialDays: CalendarClock,
  unit: Ruler,
  used: Gauge,
  usedShare: PieChart,
  value: Gauge,
  variant: Grid2x2,
  visible: Eye,
  visibleCount: Rows3,
  visibleLimit: Rows3,
  wait: Hourglass,
  warn: TriangleAlert,
  width: Ruler,
  wrapByDefault: WrapText,
  window: CalendarRange,
  year: CalendarFold,
  zebra: Rows3,
  zoom: ZoomIn,
  change: Percent,
  done: CircleCheck,
  external: ExternalLink,
  lines: Rows3,
  media: ImageIcon,
  rating: Star,
  dayFrom: Sunrise,
  dayTo: Sunset,
  weeks: CalendarRange,
  position: ListOrdered,
  tiles: LayoutGrid,
  tint: Droplet,
  unread: Bell,
  pack: Package,
  defaultPacks: Boxes,
  defaultUnit: Ruler,
  bigStep: ChevronsUp,
  late: CalendarClock,
  cardWidth: MoveHorizontal,
  activeIndex: Target,
  up: ThumbsUp,
  down: ThumbsDown,
  threshold: Gauge,
  line: Minus,
  dash: Ellipsis,
  dividerHeight: Ruler,
  space: MoveVertical,
  maxRows: Rows3,
  wordsPerMinute: Gauge,
  defaultFrom: ArrowLeftToLine,
  dashed: Ellipsis,
  waves: Radio,
  truncate: Scissors,
  env: Server,
  plan: Crown,
  warnAt: TriangleAlert,
  defaultSelected: ListChecks,
  scaleMax: Ruler,
  showMoves: ArrowDownUp,
  capacity: Gauge,
  nights: Moon,
  hoursPerDay: Clock,
  awayZone: Globe,
  minAge: UserCheck,
  softLimit: TriangleAlert,
  hardLimit: Ban,
  activeFilter: ListFilter,
  activeGroup: Boxes,
  activeLevel: Signal,
  activeTab: AppWindow,
  inviteRole: UserPlus,
  newScope: Lock,
  recoveryLeft: KeyRound,
  twoFactorOn: ShieldCheck,
  visibility: Eye,
  maxItems: ListChecks,
  headChars: ArrowLeftToLine,
  tailChars: ArrowRightToLine,
  visibleChips: Tag,
  menuWidth: MoveHorizontal,
  linkMinutes: Timer,
  trustDays: CalendarClock,
  expiresDays: Hourglass,
  minPassword: KeyRound,
  defaultStep: Milestone,
  showLock: Lock,
  showNumbers: ListOrdered,
  defaultLanguage: Languages,
  changedLine: Highlighter,
  showLegend: Captions,
  maxHeight: MoveVertical,
  stale: History,
  openDepth: ListCollapse,
  revealAll: Eye,
  showDone: ListChecks,
  kind: FileType,
  featured: Crown,
  severity: TriangleAlert,
  avatar: CircleUser,
  tier: Medal,
  defaultMethod: CreditCard,
  itemCount: Files,
  savedCount: Heart,
  caseColor: SwatchBook,
  maxPinned: Pin,
  aggregate: Sigma,
  joiner: Blend,
  startView: LayoutGrid,
  defaultCorner: PictureInPicture2,
  reconnectAfter: RotateCcw,
  hideAfter: Hourglass,
  durationMs: Clock,
  autoHideMs: Hourglass,
  found: Search,
  defaultFrequency: Repeat,
  defaultInterval: Clock,
  occurrences: ListOrdered,
  defaultPreset: CalendarRange,
  openFrom: Sunrise,
  openTo: Sunset,
  maxDays: CalendarRange,
  amount: Banknote,
  period: Repeat,
  perSeat: Coins,
  basePrice: Coins,
  includedSeats: UserCheck,
  defaultSeats: Users,
  emphasis: Bold,
  leading: ArrowLeftToLine,
  trailing: ArrowRightToLine,
  minChars: WholeWord,
  soldPercent: Percent,
  skeletons: SquareDashed,
  accentEnd: Blend,
  cut: Scissors,
  lift: ArrowUpFromLine,
  depth: ArrowDownFromLine,
  defaultCategory: Boxes,
  stock: Package,
  maxOption: Rows3,
  lowStockThreshold: TriangleAlert,
  maxWidthCh: Ruler,
  maxLength: Ruler,
  connected: Plug,
  score: Sigma,
  picked: CircleDot,
  activePreset: CalendarRange,
  collapsedHeight: Minimize2,
  expandedHeight: Maximize2,
  yearlyOff: Percent,
  codeLength: KeyRound,
  graceDays: CalendarClock,
  renewalWindowMonths: CalendarClock,
  anomalyThreshold: TriangleAlert,
  requiredSignatures: Signature,
  batchSize: Boxes,
  showDelta: Percent,
  showHost: Globe,
  provider: LogIn,
  defaultAdded: ShoppingCart,
  defaultFollowing: UserCheck,
  openFirst: ListCollapse,
  ratePerArea: Coins,
  format: FileType,
  quietOn: Moon,
  modifier: Keyboard,
  activeKind: Shapes,
  activeView: LayoutGrid,
  selectedCount: ListChecks,
  pending: Inbox,
  draftField: Type,
  running: LoaderCircle,
  defaultActive: Power,
  longWaitMinutes: Hourglass,
  activeEnv: Server,
  todayColumn: CalendarCheck,
  onCallNow: UserCheck,
  timeShare: Hourglass,
  metric: Sigma,
  region: Globe,
  activeColor: SwatchBook,
}

/** Запасной значок: тип контрола известен всегда. */
const BY_TYPE: Record<ItemControl["type"], LucideIcon> = {
  boolean: ToggleLeft,
  color: Palette,
  number: Hash,
  select: List,
  text: Type,
}

/**
 * Значки на отдельные значения. Кнопка тогда показывает не «здесь есть
 * настройка», а текущее состояние — на карточке это единственная подпись,
 * которую видно.
 */
const BY_VALUE: Record<string, Record<string, LucideIcon>> = {
  marker: {
    chevron: ChevronDown,
    dot: CircleDot,
    ring: Circle,
    triangle: Triangle,
    square: Square,
    plus: Plus,
    none: Ban,
  },
  elevation: {
    lift: SquareStack,
    ring: Scan,
    flat: Square,
  },
  glow: {
    edge: Sparkles,
    ring: Scan,
    none: Ban,
  },
  guide: {
    line: IndentIncrease,
    none: Ban,
  },
  progress: {
    bar: Gauge,
    count: Hash,
    none: Ban,
  },
  rail: {
    solid: Minus,
    dashed: Ellipsis,
    none: Ban,
  },
  stripe: {
    bar: Flag,
    ring: Scan,
    none: Ban,
  },
  divider: {
    line: Minus,
    dashed: Ellipsis,
    none: Ban,
  },
}

/**
 * Типы, которые помещаются в строку значков. Select, boolean и number
 * крутятся самой кнопкой, color открывает системную пипетку, а текст —
 * маленькое поле под кнопкой: в строку значков оно не влезает, но и
 * отправлять человека на страницу item'а ради подписи незачем.
 */
const CARD_TYPES = new Set<ItemControl["type"]>([
  "select",
  "boolean",
  "number",
  "color",
  "text",
])

export function isCardControl(control: ItemControl): boolean {
  // У числового контрола без границ круг не замкнуть: кнопка одна, и вернуться
  // к началу перебора будет нечем.
  if (control.type === "number") {
    return control.min !== undefined && control.max !== undefined
  }

  return CARD_TYPES.has(control.type)
}

export function cardControlIcon(
  control: ItemControl,
  value: ControlValue,
): LucideIcon {
  const byValue = BY_VALUE[control.prop]?.[String(value)]

  if (byValue) {
    return byValue
  }

  return BY_PROP[control.prop] ?? BY_TYPE[control.type]
}

/** Кто из контролов вынесен на карточку. Порядок задаёт сам item. */
export function pickCardControls(
  controls: ItemControl[],
  props: string[] | undefined,
): ItemControl[] {
  if (!props?.length) {
    return []
  }

  return props
    .map((prop) => controls.find((control) => control.prop === prop))
    .filter(
      (control): control is ItemControl =>
        control !== undefined && isCardControl(control),
    )
}

/**
 * Следующее значение по кругу. Кнопка одна, поэтому перебор идёт вперёд и
 * с последнего значения возвращается на первое.
 */
export function nextControlValue(
  control: ItemControl,
  value: ControlValue,
): ControlValue {
  switch (control.type) {
    case "select": {
      const index = control.options.indexOf(String(value))

      return control.options[(index + 1) % control.options.length]
    }
    case "boolean":
      return value !== true
    case "number": {
      const min = control.min ?? 0
      const max = control.max ?? min
      const next = Number(value) + 1

      return next > max ? min : next
    }
    default:
      return value
  }
}

/** Подпись кнопки: что настраивается и что стоит сейчас. */
export function cardControlTitle(
  control: ItemControl,
  value: ControlValue,
): string {
  if (control.type === "boolean") {
    return `${control.label}: ${value === true ? "on" : "off"}`
  }

  return `${control.label}: ${String(value) || "—"}`
}
