/**
 * Подписи действий в журнале. Отдельной константой с явным типом: журнал
 * индексируется строкой из базы, и литеральные ключи здесь только мешают.
 */
const LOG_ACTIONS: Record<string, string> = {
  "report.reply": "Ответ на обращение",
  "report.note": "Заметка к обращению",
  "report.status": "Смена статуса обращения",
  "report.assign": "Взял обращение",
  "user.grant_pro": "Выдал Pro",
  "user.cancel_renewal": "Отключил продление",
  "user.resume_renewal": "Включил продление",
  "user.block": "Заблокировал",
  "user.unblock": "Разблокировал",
  "user.revoke_tokens": "Отозвал ключи",
  "user.reset_limit": "Сбросил лимит месяца",
  "user.verify_email": "Подтвердил почту",
  "user.resend_verification": "Отправил письмо подтверждения",
  "user.sign_out_all": "Завершил сессии",
  "user.note": "Изменил заметку",
  "payment.sync": "Сверил платёж",
  "payment.replay": "Применил событие заново",
  "payment.mark_refunded": "Пометил возвращённым",
  "payment.receipt": "Внёс ссылку на чек",
  "partner.create": "Создал ссылку для блогера",
  "partner.delete": "Удалил ссылку для блогера",
  "setting.prices": "Изменил цены тарифов",
}

/**
 * Тексты админки. Только русские: это внутренний инструмент одного-двух
 * человек, и вторая языковая ветка здесь удваивала бы работу без читателя.
 */
export const ADMIN_TEXTS = {
  nav: {
    group: "Админ",
    summary: "Сводка",
    payments: "Платежи",
    reports: "Жалобы",
    users: "Пользователи",
    partners: "Партнёры",
    log: "Журнал действий",
  },
  partners: {
    title: "Партнёры",
    lead: "Блогеры, которым выдана реферальная ссылка, и кого они привели.",
    nameLabel: "Имя блогера",
    namePlaceholder: "Как вы его называете",
    create: "Создать ссылку",
    creating: "Создаём…",
    created: "Ссылка создана",
    failed: "Не получилось, попробуйте ещё раз",
    empty: "Ссылок пока нет.",
    columnInvite: "Приглашение",
    notClaimed: "Не зарегистрировался",
    claimed: "Зарегистрировался",
    referrals: "Рефералов",
    paid: "Оплатили",
    delete: "Удалить",
    deleteConfirm: "Удалить ссылку? Регистрироваться по ней будет нельзя.",
    open: "Открыть",
    inviteLink: "Ссылка-приглашение",
    inviteVisits: "Переходов по приглашению",
    partnerLink: "Ссылка партнёра",
    partnerVisits: "Переходов по ссылке партнёра",
    registeredAt: "Зарегистрировался",
    account: "Карточка пользователя",
    waiting: "Блогер ещё не зарегистрировался: рефералов нет.",
    referralsTitle: "Рефералы",
    referralsEmpty: "Рефералов пока нет.",
    paidTotal: "Оплачено",
    notPaid: "Не оплачивал",
    paidAt: (date: string) => `Оплатил ${date}`,
    activeUntil: (date: string) => `активна до ${date}`,
    expired: "истекла",
    more: "Показать ещё",
    rub: (amount: number) => `${amount.toLocaleString("ru-RU")} ₽`,
  },
  summary: {
    title: "Сводка",
    lead: "Что происходит с деньгами, людьми и поиском.",
    period: "Период",
    periods: { 7: "7 дней", 30: "30 дней", 90: "90 дней" },
    money: "Деньги",
    revenue: "Выручка",
    payments: "Успешных платежей",
    average: "Средний чек",
    activeSubs: "Активных подписок",
    stuck: "Зависшие платежи",
    stuckNote: "В статусе «ожидает» дольше 30 минут",
    people: "Люди",
    signups: "Регистраций",
    verified: "Подтвердили почту",
    active: "Брали компоненты",
    exhausted: "Упёрлись в лимит",
    newPro: "Новых Pro",
    churn: "Отписались",
    discovery: "Поиск и приглашения",
    topQueries: "Что ищут",
    emptyQueries: "Искали и не нашли",
    visits: "Переходов по ссылкам",
    invited: "Из них зарегистрировались",
    invitedPaid: "Из них оплатили",
    noData: "За этот период данных нет.",
    since: (date: string) => `с ${date}`,
    versus: (value: string) => `было ${value}`,
    versusPeriod: "к прошлому периоду",
    revenueChart: "Выручка по дням",
    signupsChart: "Регистрации по дням",
    activeChart: "Брали компоненты, людей в день",
    attention: "Требует внимания",
    attentionNote: "Плитка ведёт к списку с нужным фильтром.",
    funnel: "Воронка новых пользователей",
    funnelNote: "Люди, зарегистрировавшиеся за период, и что они сделали дальше.",
    funnelVerified: "Подтвердили почту",
    funnelActive: "Взяли компонент",
    funnelPro: "Оформили Pro",
    searchTitle: "Поиск",
    referralsTitle: "Приглашения",
  },
  payments: {
    title: "Платежи",
    lead: "Все платежи ЮKassa, какими их видит наша база.",
    search: "Почта или идентификатор платежа",
    all: "Все",
    status: {
      succeeded: "Оплачен",
      pending: "Ожидает",
      canceled: "Отменён",
      refunded: "Возвращён",
      unknown: "Неизвестен",
    },
    empty: "Платежей по этим условиям нет.",
    more: "Показать ещё",
    export: "Выгрузить CSV",
    find: "Найти",
    sum: "Сумма на странице",
    columnDate: "Дата",
    columnUser: "Пользователь",
    columnAmount: "Сумма",
    columnStatus: "Статус",
    columnPlan: "Тариф",
    open: "Открыть",
    cardTitle: "Платёж",
    yookassaId: "Идентификатор ЮKassa",
    created: "Создан",
    paid: "Оплачен",
    payload: "Ответ ЮKassa",
    sync: "Сверить с ЮKassa",
    syncing: "Сверяем…",
    syncNote:
      "Перезапросим статус по API. Нужно там, где деньги списались, а вебхук не дошёл.",
    replay: "Применить событие заново",
    replaying: "Применяем…",
    replayNote:
      "Прогонит сохранённый ответ через тот же обработчик, что и вебхук. Повторная обработка того же платежа подписку не задваивает.",
    markRefunded: "Пометить возвращённым",
    markRefundedNote:
      "Только отметка в базе. Сам возврат делается в кабинете ЮKassa: двигать деньги из нашего кода мы не будем.",
    reason: "Причина",
    done: "Готово",
    failed: "Не получилось. Попробуйте ещё раз.",
    subscription: "Подписка",
    receipt: "Чек",
    receiptNote:
      "Ссылка на чек из «Мой налог». Пользователь увидит её в кабинете в разделе «Оплата». Пустое поле убирает ссылку.",
    receiptPlaceholder: "https://lknpd.nalog.ru/api/v1/receipt/…",
    receiptSave: "Сохранить ссылку",
    receiptSaving: "Сохраняем…",
    receiptMissing: "не внесён",
    prices: "Цены тарифов",
    pricesNote:
      "Цена Pro в рублях, без копеек. Энтерпрайз считается вдвое дороже сам. Новая цена сразу уходит на витрину и в следующие списания; уже оплаченные периоды не меняются.",
    priceMonthly: "Pro на месяц, ₽",
    priceYearly: "Pro на год, ₽",
    pricesSave: "Сохранить цены",
    pricesSaving: "Сохраняем…",
    pricesDefault: "по умолчанию",
  },
  reports: {
    title: "Жалобы",
    lead: "Обращения из каталога, кабинета и публичной формы.",
    kind: {
      component: "Компонент",
      support: "Поддержка",
      legal: "Права",
    },
    status: {
      new: "Новое",
      in_progress: "В работе",
      answered: "Отвечено",
      closed: "Закрыто",
      spam: "Спам",
    },
    mine: "Только мои",
    empty: "Обращений по этим условиям нет.",
    age: (days: number) =>
      days === 0 ? "сегодня" : days === 1 ? "1 день" : `${days} дн.`,
    open: "Открыть",
    from: "От кого",
    about: "О компоненте",
    take: "Взять себе",
    taken: (email: string) => `В работе у ${email}`,
    reply: "Ответ заявителю",
    replyNote: "Уйдёт письмом и сохранится в переписке.",
    send: "Отправить ответ",
    sending: "Отправляем…",
    note: "Внутренняя заметка",
    noteNote: "Видна только администраторам.",
    addNote: "Сохранить заметку",
    setStatus: "Статус",
    save: "Сохранить",
    saved: "Сохранено",
    failed: "Не получилось. Попробуйте ещё раз.",
    messageUser: "Заявитель",
    messageAdmin: "Поддержка",
    messageNote: "Заметка",
    more: "Показать ещё",
  },
  users: {
    title: "Пользователи",
    lead: "Поиск по почте и имени, карточка с историей и действиями.",
    search: "Почта или имя",
    empty: "Никого не нашлось.",
    columnUser: "Пользователь",
    columnPlan: "Тариф",
    columnJoined: "Регистрация",
    columnState: "Состояние",
    find: "Найти",
    total: (n: number) => `Показано ${n}`,
    verified: "Почта подтверждена",
    unverified: "Почта не подтверждена",
    blocked: "Заблокирован",
    open: "Открыть",
    more: "Показать ещё",
    card: {
      profile: "Профиль",
      joined: (date: string) => `Зарегистрирован ${date}`,
      locale: "Язык писем",
      subscription: "Подписка",
      usage: "Расход лимита",
      usageMonth: (month: string, count: number) => `${month}: ${count}`,
      tokens: "Ключи установки",
      sessions: "Сессии",
      reports: "Обращения",
      payments: "Платежи",
      note: "Заметка поддержки",
      noteSave: "Сохранить заметку",
      actions: "Действия",
      nothing: "Пусто",
    },
    actions: {
      grantPro: "Выдать Pro",
      grantProNote:
        "Начисляется как бонусные дни: в кабинете человека они так и называются и не обещают списаний.",
      days: "Дней",
      reason: "Причина",
      reasonRequired: "Причина обязательна: она попадёт в журнал.",
      grant: "Начислить",
      block: "Заблокировать",
      unblock: "Разблокировать",
      blockNote:
        "Закроет вход и выдачу исходников, завершит все сессии. Причина попадёт в журнал.",
      revokeTokens: "Отозвать ключи",
      revokeTokensNote:
        "Все действующие ключи установки перестанут работать — нужно при утечке ключа.",
      resetLimit: "Сбросить лимит месяца",
      resetLimitNote: "Удалит расход текущего месяца. История останется.",
      verifyEmail: "Подтвердить почту вручную",
      verifyEmailNote:
        "Когда письма не доходят, а владение адресом доказано перепиской.",
      resendVerification: "Отправить письмо подтверждения",
      signOutAll: "Завершить все сессии",
      confirm: "Подтвердить",
      cancel: "Отмена",
      done: "Готово",
      failed: "Не получилось. Попробуйте ещё раз.",
    },
  },
  log: {
    title: "Журнал действий",
    lead: "Кто, что и над кем сделал. Записи не редактируются и не удаляются.",
    empty: "Записей пока нет.",
    columnWhen: "Когда",
    columnWho: "Кто",
    columnWhat: "Что",
    columnTarget: "Над кем",
    more: "Показать ещё",
    actions: LOG_ACTIONS,
  },
  common: {
    back: "Назад",
    cancel: "Отмена",
    nothing: "—",
  },
} as const

/** Формы обращений: их видят пользователи, поэтому тексты двуязычные. */
export const REPORT_FORM_TEXTS = {
  ru: {
    trigger: "Сообщить о проблеме",
    title: "Что не так с компонентом?",
    supportTitle: "Написать в поддержку",
    legalTitle: "Претензия по правам на материал",
    legalLead:
      "Опишите материал и основание претензии. Мы ответим на указанный адрес.",
    supportLead:
      "Опишите, что случилось. Мы отвечаем на почту аккаунта в течение рабочего дня.",
    reason: "Что произошло",
    reasons: {
      broken: "Не работает",
      looks: "Выглядит не так, как в превью",
      agent: "Агент не смог поставить",
      other: "Другое",
    },
    subject: "Тема",
    message: "Подробности",
    messageHint: "От 20 символов: что делали и что получилось.",
    email: "Почта для ответа",
    send: "Отправить",
    sending: "Отправляем…",
    sent: "Обращение принято",
    sentNote:
      "Мы ответим письмом. Номер обращения придёт на указанный адрес.",
    close: "Закрыть",
    tooOften: "Слишком часто. Попробуйте через несколько минут.",
    failed: "Не получилось отправить. Попробуйте ещё раз.",
    required: "Заполните тему и подробности.",
  },
  en: {
    trigger: "Report a problem",
    title: "What is wrong with this component?",
    supportTitle: "Contact support",
    legalTitle: "Content rights claim",
    legalLead:
      "Describe the material and the grounds for the claim. We reply to the address you leave.",
    supportLead:
      "Tell us what happened. We answer to the account email within a working day.",
    reason: "What happened",
    reasons: {
      broken: "It does not work",
      looks: "It looks different from the preview",
      agent: "The agent could not install it",
      other: "Something else",
    },
    subject: "Subject",
    message: "Details",
    messageHint: "At least 20 characters: what you did and what you got.",
    email: "Email for the reply",
    send: "Send",
    sending: "Sending…",
    sent: "We have your report",
    sentNote: "We will reply by email. The reference number goes to that address.",
    close: "Close",
    tooOften: "Too often. Try again in a few minutes.",
    failed: "Could not send. Please try again.",
    required: "Fill in the subject and the details.",
  },
} as const
