/**
 * Подписи действий в журнале. Отдельной константой с явным типом: журнал
 * индексируется строкой из базы, и литеральные ключи здесь только мешают.
 */
const LOG_ACTIONS: Record<string, string> = {
  "report.reply": "Ответ на обращение",
  "report.note": "Заметка к обращению",
  "report.status": "Смена статуса обращения",
  "report.assign": "Взял обращение",
  "user.grant_pro": "Выдал PRO",
  "user.cancel_renewal": "Отключил продление",
  "user.resume_renewal": "Включил продление",
  "user.block": "Заблокировал",
  "user.unblock": "Разблокировал",
  "user.revoke_tokens": "Отозвал ключи",
  "user.reset_limit": "Сбросил лимит месяца",
  "user.verify_email": "Подтвердил почту",
  "user.resend_verification": "Отправил письмо подтверждения",
  "user.sign_out_all": "Завершил сессии",
  "user.note": "Изменил заметку",
  "payment.sync": "Сверил платёж",
  "payment.replay": "Применил событие заново",
  "payment.mark_refunded": "Пометил возвращённым",
  "payment.receipt": "Внёс ссылку на чек",
  "partner.create": "Создал ссылку для блогера",
  "partner.delete": "Удалил ссылку для блогера",
  "partner.promo": "Изменил промокод блогера",
  "partner.payout": "Записал выплату блогеру",
  "partner.payout_approve": "Согласовал заявку на вывод",
  "partner.payout_pay": "Отметил выплату по заявке",
  "partner.payout_reject": "Отклонил заявку на вывод",
  "setting.prices": "Изменил цены тарифов",
}

/**
 * Тексты админки. Только русские: это внутренний инструмент одного-двух
 * человек, и вторая языковая ветка здесь удваивала бы работу без читателя.
 */
export const ADMIN_TEXTS = {
  nav: {
    group: "Админ",
    summary: "Сводка",
    payments: "Платежи",
    reports: "Жалобы",
    users: "Пользователи",
    partners: "Партнёры",
    payouts: "Выплаты",
    log: "Журнал действий",
  },
  payouts: {
    title: "Заявки на вывод",
    lead: "Блогеры запрашивают вывод комиссии. Согласуйте заявку, переведите деньги по реквизитам и отметьте выплату, приложив ссылку на чек блогера.",
    empty: "Заявок на рассмотрении нет.",
    historyTitle: "История",
    inn: "ИНН",
    details: "Реквизиты",
    receipt: "чек",
    receiptPlaceholder: "https:// ссылка на чек «Мой налог»",
    approve: "Согласовать",
    markPaid: "Отметить выплату",
    reject: "Отклонить",
    notePlaceholder: "заметка",
    doneApproved: "Заявка согласована",
    donePaid: "Выплата отмечена",
    doneRejected: "Заявка отклонена",
    failed: "Не получилось, попробуйте ещё раз",
  },
  partners: {
    title: "Партнёры",
    lead: "Блогеры, которым выдана реферальная ссылка, и кого они привели.",
    nameLabel: "Имя блогера",
    namePlaceholder: "Как вы его называете",
    create: "Создать ссылку",
    creating: "Создаём…",
    created: "Ссылка создана",
    failed: "Не получилось, попробуйте ещё раз",
    empty: "Ссылок пока нет.",
    columnInvite: "Приглашение",
    notClaimed: "Не зарегистрировался",
    claimed: "Зарегистрировался",
    referrals: "Рефералов",
    paid: "Оплатили",
    delete: "Удалить",
    deleteConfirm: "Удалить ссылку? Регистрироваться по ней будет нельзя.",
    open: "Открыть",
    inviteLink: "Ссылка-приглашение",
    inviteVisits: "Переходов по приглашению",
    partnerLink: "Ссылка партнёра",
    partnerVisits: "Переходов по ссылке партнёра",
    registeredAt: "Зарегистрировался",
    account: "Карточка пользователя",
    waiting: "Блогер ещё не зарегистрировался: рефералов нет.",
    referralsTitle: "Рефералы",
    referralsEmpty: "Рефералов пока нет.",
    paidTotal: "Оплачено",
    notPaid: "Не оплачивал",
    paidAt: (date: string) => `Оплатил ${date}`,
    activeUntil: (date: string) => `активна до ${date}`,
    expired: "истекла",
    more: "Показать ещё",
    rub: (amount: number) => `${amount.toLocaleString("ru-RU")} ₽`,
    promoTitle: "Промокод",
    promoNote:
      "Ник блогера. Зритель вводит его на тарифах и получает скидку на первый платёж; платёж закрепляется за блогером. Смена кода старые платежи не трогает.",
    promoCode: "Промокод",
    promoPlaceholder: "ник, латиницей",
    promoPercent: "Скидка, %",
    promoPercentDefault: "пусто = общая",
    promoActive: "Действует",
    promoSave: "Сохранить промокод",
    promoSaving: "Сохраняем…",
    promoSaved: "Промокод сохранён",
    promoNone: "не задан",
    promoOff: "выключен",
    promoPayments: "Оплат по промокоду",
    promoRevenue: "Выручка по промокоду",
    promoDiscount: "Скидок выдано",
    promoCommission: "Комиссия блогера",
    payoutTitle: "Выплаты комиссии",
    payoutEarned: "Начислено",
    payoutPaid: "Выплачено",
    payoutPending: "К выплате",
    payoutAmount: "Сумма, ₽",
    payoutNote: "Заметка",
    payoutNotePlaceholder: "перевод, дата, чек",
    payoutSave: "Записать выплату",
    payoutSaving: "Записываем…",
    payoutSaved: "Выплата записана",
    payoutInn: "ИНН",
    payoutDetails: "Реквизиты",
    payoutNone: "не заполнены",
    payoutsEmpty: "Выплат ещё не было.",
  },
  summary: {
    title: "Сводка",
    lead: "Что происходит с деньгами, людьми и поиском.",
    period: "Период",
    periods: { 7: "7 дней", 30: "30 дней", 90: "90 дней" },
    money: "Деньги",
    revenue: "Выручка",
    payments: "Успешных платежей",
    average: "Средний чек",
    activeSubs: "Активных подписок",
    stuck: "Зависшие платежи",
    stuckNote: "В статусе «ожидает» дольше 30 минут",
    people: "Люди",
    signups: "Регистраций",
    verified: "Подтвердили почту",
    active: "Брали компоненты",
    exhausted: "Упёрлись в лимит",
    newPro: "Новых PRO",
    churn: "Отписались",
    discovery: "Поиск и приглашения",
    topQueries: "Что ищут",
    emptyQueries: "Искали и не нашли",
    visits: "Переходов по ссылкам",
    invited: "Из них зарегистрировались",
    invitedPaid: "Из них оплатили",
    noData: "За этот период данных нет.",
    since: (date: string) => `с ${date}`,
    versus: (value: string) => `было ${value}`,
    versusPeriod: "к прошлому периоду",
    revenueChart: "Выручка по дням",
    signupsChart: "Регистрации по дням",
    activeChart: "Брали компоненты, людей в день",
    attention: "Требует внимания",
    attentionNote: "Плитка ведёт к списку с нужным фильтром.",
    funnel: "Воронка новых пользователей",
    funnelNote:
      "Люди, зарегистрировавшиеся за период, и что они сделали дальше.",
    funnelVerified: "Подтвердили почту",
    funnelActive: "Взяли компонент",
    funnelPro: "Оформили PRO",
    searchTitle: "Поиск",
    referralsTitle: "Приглашения",
  },
  payments: {
    title: "Платежи",
    lead: "Все платежи ЮKassa, какими их видит наша база.",
    search: "Почта или идентификатор платежа",
    all: "Все",
    status: {
      succeeded: "Оплачен",
      pending: "Ожидает",
      canceled: "Отменён",
      refunded: "Возвращён",
      unknown: "Неизвестен",
    },
    empty: "Платежей по этим условиям нет.",
    more: "Показать ещё",
    export: "Выгрузить CSV",
    find: "Найти",
    sum: "Сумма на странице",
    columnDate: "Дата",
    columnUser: "Пользователь",
    columnAmount: "Сумма",
    columnStatus: "Статус",
    columnPlan: "Тариф",
    columnPromo: "Промокод",
    open: "Открыть",
    cardTitle: "Платёж",
    yookassaId: "Идентификатор ЮKassa",
    created: "Создан",
    paid: "Оплачен",
    payload: "Ответ ЮKassa",
    sync: "Сверить с ЮKassa",
    syncing: "Сверяем…",
    syncNote:
      "Перезапросим статус по API. Нужно там, где деньги списались, а вебхук не дошёл.",
    replay: "Применить событие заново",
    replaying: "Применяем…",
    replayNote:
      "Прогонит сохранённый ответ через тот же обработчик, что и вебхук. Повторная обработка того же платежа подписку не задваивает.",
    markRefunded: "Пометить возвращённым",
    markRefundedNote:
      "Только отметка в базе. Сам возврат делается в кабинете ЮKassa: двигать деньги из нашего кода мы не будем.",
    reason: "Причина",
    done: "Готово",
    failed: "Не получилось. Попробуйте ещё раз.",
    subscription: "Подписка",
    receipt: "Чек",
    receiptNote:
      "Ссылка на чек из «Мой налог». Пользователь увидит её в кабинете в разделе «Оплата». Пустое поле убирает ссылку.",
    receiptPlaceholder: "https://lknpd.nalog.ru/api/v1/receipt/…",
    receiptSave: "Сохранить ссылку",
    receiptSaving: "Сохраняем…",
    receiptMissing: "не внесён",
    prices: "Цены тарифов",
    pricesNote:
      "Цена PRO в рублях, без копеек. Энтерпрайз считается вдвое дороже сам. Новая цена сразу уходит на витрину и в следующие списания; уже оплаченные периоды не меняются.",
    priceMonthly: "PRO на месяц, ₽",
    priceYearly: "PRO на год, ₽",
    pricesSave: "Сохранить цены",
    pricesSaving: "Сохраняем…",
    pricesDefault: "по умолчанию",
    promoPercent: "Скидка по промокоду, %",
    commissionPercent: "Комиссия блогера, %",
    promoPercentNote:
      "Скидка блогера на первый платёж. Цена после скидки округляется до «…90»: при 30 % месяц 690 → 490, год 5900 → 4090. У конкретного блогера процент можно переопределить на его странице. Комиссия блогера — отдельная доля от собранной по его коду суммы; она видна блогеру в его кабинете, выплаты вне платформы.",
  },
  reports: {
    title: "Жалобы",
    lead: "Обращения из каталога, кабинета и публичной формы.",
    kind: {
      component: "Компонент",
      support: "Поддержка",
      legal: "Права",
    },
    status: {
      new: "Новое",
      in_progress: "В работе",
      answered: "Отвечено",
      closed: "Закрыто",
      spam: "Спам",
    },
    mine: "Только мои",
    empty: "Обращений по этим условиям нет.",
    age: (days: number) =>
      days === 0 ? "сегодня" : days === 1 ? "1 день" : `${days} дн.`,
    open: "Открыть",
    from: "От кого",
    about: "О компоненте",
    take: "Взять себе",
    taken: (email: string) => `В работе у ${email}`,
    reply: "Ответ заявителю",
    replyNote: "Уйдёт письмом и сохранится в переписке.",
    send: "Отправить ответ",
    sending: "Отправляем…",
    note: "Внутренняя заметка",
    noteNote: "Видна только администраторам.",
    addNote: "Сохранить заметку",
    setStatus: "Статус",
    save: "Сохранить",
    saved: "Сохранено",
    failed: "Не получилось. Попробуйте ещё раз.",
    messageUser: "Заявитель",
    messageAdmin: "Поддержка",
    messageNote: "Заметка",
    more: "Показать ещё",
  },
  users: {
    title: "Пользователи",
    lead: "Поиск по почте и имени, карточка с историей и действиями.",
    search: "Почта или имя",
    empty: "Никого не нашлось.",
    columnUser: "Пользователь",
    columnPlan: "Тариф",
    columnJoined: "Регистрация",
    columnState: "Состояние",
    find: "Найти",
    total: (n: number) => `Показано ${n}`,
    verified: "Почта подтверждена",
    unverified: "Почта не подтверждена",
    blocked: "Заблокирован",
    open: "Открыть",
    more: "Показать ещё",
    card: {
      profile: "Профиль",
      joined: (date: string) => `Зарегистрирован ${date}`,
      locale: "Язык писем",
      subscription: "Подписка",
      usage: "Расход лимита",
      usageMonth: (month: string, count: number) => `${month}: ${count}`,
      tokens: "Ключи установки",
      sessions: "Сессии",
      reports: "Обращения",
      payments: "Платежи",
      note: "Заметка поддержки",
      noteSave: "Сохранить заметку",
      actions: "Действия",
      nothing: "Пусто",
    },
    actions: {
      grantPro: "Выдать PRO",
      grantProNote:
        "Начисляется как бонусные дни: в кабинете человека они так и называются и не обещают списаний.",
      days: "Дней",
      reason: "Причина",
      reasonRequired: "Причина обязательна: она попадёт в журнал.",
      grant: "Начислить",
      block: "Заблокировать",
      unblock: "Разблокировать",
      blockNote:
        "Закроет вход и выдачу исходников, завершит все сессии. Причина попадёт в журнал.",
      revokeTokens: "Отозвать ключи",
      revokeTokensNote:
        "Все действующие ключи установки перестанут работать — нужно при утечке ключа.",
      resetLimit: "Сбросить лимит месяца",
      resetLimitNote: "Удалит расход текущего месяца. История останется.",
      verifyEmail: "Подтвердить почту вручную",
      verifyEmailNote:
        "Когда письма не доходят, а владение адресом доказано перепиской.",
      resendVerification: "Отправить письмо подтверждения",
      signOutAll: "Завершить все сессии",
      confirm: "Подтвердить",
      cancel: "Отмена",
      done: "Готово",
      failed: "Не получилось. Попробуйте ещё раз.",
    },
  },
  log: {
    title: "Журнал действий",
    lead: "Кто, что и над кем сделал. Записи не редактируются и не удаляются.",
    empty: "Записей пока нет.",
    columnWhen: "Когда",
    columnWho: "Кто",
    columnWhat: "Что",
    columnTarget: "Над кем",
    more: "Показать ещё",
    actions: LOG_ACTIONS,
  },
  common: {
    back: "Назад",
    cancel: "Отмена",
    nothing: "—",
  },
} as const

const LOG_ACTIONS_EN: Record<string, string> = {
  "report.reply": "Response to request",
  "report.note": "Note for appeal",
  "report.status": "Change request status",
  "report.assign": "Received an appeal",
  "user.grant_pro": "Issued PRO",
  "user.cancel_renewal": "Disabled renewal",
  "user.resume_renewal": "Enabled renewal",
  "user.block": "Blocked",
  "user.unblock": "Unlocked",
  "user.revoke_tokens": "Revoked keys",
  "user.reset_limit": "Reset the month limit",
  "user.verify_email": "Confirmed email",
  "user.resend_verification": "Sent confirmation email",
  "user.sign_out_all": "Ended sessions",
  "user.note": "Changed note",
  "payment.sync": "Reconciled payment",
  "payment.replay": "Reapplied the event",
  "payment.mark_refunded": "Marked returned",
  "payment.receipt": "Added a link to the check",
  "partner.create": "Created a link for the blogger",
  "partner.delete": "Removed link for blogger",
  "partner.promo": "Changed the blogger's promotional code",
  "partner.payout": "Recorded payment to blogger",
  "partner.payout_approve": "Approved the withdrawal request",
  "partner.payout_pay": "Noted payment on application",
  "partner.payout_reject": "Rejected withdrawal request",
  "setting.prices": "Changed tariff prices",
}

/**
 * Admin texts. Only Russians: this is an internal tool of one or two
 * person, and a second language branch here would double the work without a reader.
 */
export const ADMIN_TEXTS_EN = {
  nav: {
    group: "Admin",
    summary: "Summary",
    payments: "Payments",
    reports: "Complaints",
    users: "Users",
    partners: "Partners",
    payouts: "Payments",
    log: "Action Log",
  },
  payouts: {
    title: "Withdrawal requests",
    lead: "Bloggers request commission withdrawal. Agree on the application, transfer the money using the details and mark the payment by attaching a link to the blogger’s check.",
    empty: "No applications pending.",
    historyTitle: "History",
    inn: "Taxpayer Identification Number",
    details: "Details",
    receipt: "check",
    receiptPlaceholder: "https:// link to the “My Tax” check",
    approve: "Agree",
    markPaid: "Mark payment",
    reject: "Reject",
    notePlaceholder: "note",
    doneApproved: "Application approved",
    donePaid: "Payment marked",
    doneRejected: "Application rejected",
    failed: "It didn't work, try again",
  },
  partners: {
    title: "Partners",
    lead: "Bloggers who received a referral link and who they referred.",
    nameLabel: "Blogger name",
    namePlaceholder: "What do you call it",
    create: "Create link",
    creating: "Creating...",
    created: "Link created",
    failed: "It didn't work, try again",
    empty: "No links yet.",
    columnInvite: "Invitation",
    notClaimed: "Not registered",
    claimed: "Registered",
    referrals: "Referrals",
    paid: "Paid",
    delete: "Delete",
    deleteConfirm: "Remove link? It will not be possible to register using it.",
    open: "Open",
    inviteLink: "Invitation link",
    inviteVisits: "Clicks by invitation",
    partnerLink: "Partner link",
    partnerVisits: "Clicks on partner links",
    registeredAt: "Registered",
    account: "User card",
    waiting: "Blogger has not registered yet: no referrals.",
    referralsTitle: "Referrals",
    referralsEmpty: "No referrals yet.",
    paidTotal: "Paid",
    notPaid: "Didn't pay",
    paidAt: (date: string) => `Paid ${date}`,
    activeUntil: (date: string) => `active until ${date}`,
    expired: "has expired",
    more: "Show more",
    rub: (amount: number) => `${amount.toLocaleString("ru-RU")} ₽`,
    promoTitle: "Promo code",
    promoNote:
      "Blogger's nickname. The viewer enters it on the tariffs and receives a discount on the first payment; The payment is assigned to the blogger. Changing the code does not affect old payments.",
    promoCode: "Promo code",
    promoPlaceholder: "nickname, Latin",
    promoPercent: "Discount, %",
    promoPercentDefault: "empty = general",
    promoActive: "Valid",
    promoSave: "Save promo code",
    promoSaving: "Save...",
    promoSaved: "Promo code saved",
    promoNone: "not specified",
    promoOff: "disabled",
    promoPayments: "Payment using promotional code",
    promoRevenue: "Promo code revenue",
    promoDiscount: "Discounts issued",
    promoCommission: "Blogger commission",
    payoutTitle: "Commission Payments",
    payoutEarned: "Accrued",
    payoutPaid: "Paid",
    payoutPending: "Due",
    payoutAmount: "Amount, ₽",
    payoutNote: "Note",
    payoutNotePlaceholder: "transfer, date, check",
    payoutSave: "Record payment",
    payoutSaving: "Recording...",
    payoutSaved: "Payment recorded",
    payoutInn: "Taxpayer Identification Number",
    payoutDetails: "Details",
    payoutNone: "are empty",
    payoutsEmpty: "There have been no payments yet.",
  },
  summary: {
    title: "Summary",
    lead: "What happens to money, people and search.",
    period: "Period",
    periods: { 7: "7 days", 30: "30 days", 90: "90 days" },
    money: "Money",
    revenue: "Revenue",
    payments: "Successful payments",
    average: "Average check",
    activeSubs: "Active subscriptions",
    stuck: "Stuck payments",
    stuckNote: "In “waiting” status longer 30 minutes",
    people: "People",
    signups: "Registrations",
    verified: "Confirmed email",
    active: "Took the components",
    exhausted: "We hit the limit",
    newPro: "New PRO",
    churn: "Unsubscribed",
    discovery: "Search and invitations",
    topQueries: "What are they looking for?",
    emptyQueries: "We searched and did not find",
    visits: "Link clicks",
    invited: "Of these registered",
    invitedPaid: "Paid from them",
    noData: "No data available for this period.",
    since: (date: string) => `s ${date}`,
    versus: (value: string) => `was ${value}`,
    versusPeriod: "to the previous period",
    revenueChart: "Revenue by day",
    signupsChart: "Registrations by day",
    activeChart: "We took components, people per day",
    attention: "Requires attention",
    attentionNote: "The tile leads to a list with the desired filter.",
    funnel: "New user funnel",
    funnelNote:
      "People who registered during the period and what they did next.",
    funnelVerified: "Confirmed email",
    funnelActive: "Took the component",
    funnelPro: "Completed PRO",
    searchTitle: "Search",
    referralsTitle: "Invitations",
  },
  payments: {
    title: "Payments",
    lead: "All payments UKassa, as our base sees them.",
    search: "Mail or payment ID",
    all: "All",
    status: {
      succeeded: "Paid",
      pending: "Waiting",
      canceled: "Canceled",
      refunded: "Returned",
      unknown: "Unknown",
    },
    empty: "There are no payments under these terms.",
    more: "Show more",
    export: "Unload CSV",
    find: "Find",
    sum: "Amount on page",
    columnDate: "Date",
    columnUser: "User",
    columnAmount: "Amount",
    columnStatus: "Status",
    columnPlan: "Tariff",
    columnPromo: "Promo code",
    open: "Open",
    cardTitle: "Payment",
    yookassaId: "Identifier YuKassa",
    created: "Created",
    paid: "Paid",
    payload: "Reply YuKassa",
    sync: "Check with YuKassa",
    syncing: "Let's check...",
    syncNote:
      "Let's re-query the status by API. Needed where the money was debited, but the webhook did not arrive.",
    replay: "Reapply event",
    replaying: "We apply...",
    replayNote:
      "Will run the saved response through the same handler as the webhook. Repeated processing of the same payment does not double the subscription.",
    markRefunded: "Mark returned",
    markRefundedNote:
      "Only a mark in the database. The return itself is made in Yu's officeKassa: we will not move money from our code.",
    reason: "Reason",
    done: "Done",
    failed: "It didn't work. Try again.",
    subscription: "Subscription",
    receipt: "Check",
    receiptNote:
      "Link to receipt from “My Tax”. The user will see it in the account in the “Payment” section. An empty field removes the link.",
    receiptPlaceholder: "https://lknpd.nalog.ru/api/v1/receipt/…",
    receiptSave: "Save link",
    receiptSaving: "Save...",
    receiptMissing: "not entered",
    prices: "Tariff prices",
    pricesNote:
      "Price PRO in rubles, without kopecks. Enterprise is considered twice as expensive itself. The new price immediately goes to the storefront and to subsequent write-offs; periods already paid for do not change.",
    priceMonthly: "PRO for a month, ₽",
    priceYearly: "PRO for a year, ₽",
    pricesSave: "Save prices",
    pricesSaving: "Save...",
    pricesDefault: "default",
    promoPercent: "Discount using promotional code, %",
    commissionPercent: "Blogger commission, %",
    promoPercentNote:
      "Blogger discount on first payment. The price after the discount is rounded up to “...90»: at 30 % month 690 → 490, year 5900 → 4090. For a specific blogger, the percentage can be overridden on his page. The blogger’s commission is a separate share of the amount collected using his code; it is visible to the blogger in his account, payments are made outside the platform.",
  },
  reports: {
    title: "Complaints",
    lead: "Appeals from the catalogue, account and public form.",
    kind: {
      component: "Component",
      support: "Support",
      legal: "Rights",
    },
    status: {
      new: "New",
      in_progress: "In progress",
      answered: "Answered",
      closed: "Closed",
      spam: "Spam",
    },
    mine: "Only mine",
    empty: "There are no requests for these conditions.",
    age: (days: number) =>
      days === 0 ? "today" : days === 1 ? "1 day" : `${days} days`,
    open: "Open",
    from: "From",
    about: "About the component",
    take: "Take it for yourself",
    taken: (email: string) => `In work ${email}`,
    reply: "Response to applicant",
    replyNote: "Will be sent by letter and saved in correspondence.",
    send: "Send reply",
    sending: "Sending...",
    note: "Internal note",
    noteNote: "Visible only to administrators.",
    addNote: "Save note",
    setStatus: "Status",
    save: "Save",
    saved: "Saved",
    failed: "It didn't work. Try again.",
    messageUser: "Applicant",
    messageAdmin: "Support",
    messageNote: "Note",
    more: "Show more",
  },
  users: {
    title: "Users",
    lead: "Search by email and name, card with history and actions.",
    search: "Mail or name",
    empty: "No one was found.",
    columnUser: "User",
    columnPlan: "Tariff",
    columnJoined: "Registration",
    columnState: "Status",
    find: "Find",
    total: (n: number) => `Shown ${n}`,
    verified: "Email confirmed",
    unverified: "Email not confirmed",
    blocked: "Blocked",
    open: "Open",
    more: "Show more",
    card: {
      profile: "Profile",
      joined: (date: string) => `Registered ${date}`,
      locale: "Letter language",
      subscription: "Subscription",
      usage: "Limit consumption",
      usageMonth: (month: string, count: number) => `${month}: ${count}`,
      tokens: "Installation keys",
      sessions: "Sessions",
      reports: "Appeals",
      payments: "Payments",
      note: "Support Note",
      noteSave: "Save note",
      actions: "Actions",
      nothing: "Empty",
    },
    actions: {
      grantPro: "Issue PRO",
      grantProNote:
        "Accrued as bonus days: in a person’s account they are called that and do not promise write-offs.",
      days: "Days",
      reason: "Reason",
      reasonRequired: "The reason is mandatory: it will end up in the journal.",
      grant: "Accrue",
      block: "Block",
      unblock: "Unlock",
      blockNote:
        "Closes the input and distribution of sources, ends all sessions. The reason will go into the journal.",
      revokeTokens: "Revoke keys",
      revokeTokensNote:
        "All current installation keys will stop working - necessary if the key leaks.",
      resetLimit: "Reset month limit",
      resetLimitNote:
        "Will delete the current month's expense. The story will remain.",
      verifyEmail: "Confirm email manually",
      verifyEmailNote:
        "When letters do not arrive, but ownership of the address is proven by correspondence.",
      resendVerification: "Send confirmation email",
      signOutAll: "End all sessions",
      confirm: "Confirm",
      cancel: "Cancel",
      done: "Done",
      failed: "It didn't work. Try again.",
    },
  },
  log: {
    title: "Action Log",
    lead: "Who did what to whom. Entries are not edited or deleted.",
    empty: "No entries yet.",
    columnWhen: "When",
    columnWho: "Who",
    columnWhat: "What",
    columnTarget: "Over whom",
    more: "Show more",
    actions: LOG_ACTIONS_EN,
  },
  common: {
    back: "Back",
    cancel: "Cancel",
    nothing: "—",
  },
} as const

export function getAdminTexts(locale: "ru" | "en") {
  return locale === "en" ? ADMIN_TEXTS_EN : ADMIN_TEXTS
}

/** Формы обращений: их видят пользователи, поэтому тексты двуязычные. */
export const REPORT_FORM_TEXTS = {
  ru: {
    trigger: "Сообщить о проблеме",
    title: "Что не так с компонентом?",
    supportTitle: "Написать в поддержку",
    legalTitle: "Претензия по правам на материал",
    legalLead:
      "Опишите материал и основание претензии. Мы ответим на указанный адрес.",
    supportLead:
      "Опишите, что случилось. Мы отвечаем на почту аккаунта в течение рабочего дня.",
    reason: "Что произошло",
    reasons: {
      broken: "Не работает",
      looks: "Выглядит не так, как в превью",
      agent: "Агент не смог поставить",
      other: "Другое",
    },
    subject: "Тема",
    message: "Подробности",
    messageHint: "От 20 символов: что делали и что получилось.",
    email: "Почта для ответа",
    send: "Отправить",
    sending: "Отправляем…",
    sent: "Обращение принято",
    sentNote: "Мы ответим письмом. Номер обращения придёт на указанный адрес.",
    close: "Закрыть",
    tooOften: "Слишком часто. Попробуйте через несколько минут.",
    failed: "Не получилось отправить. Попробуйте ещё раз.",
    required: "Заполните тему и подробности.",
  },
  en: {
    trigger: "Report a problem",
    title: "What is wrong with this component?",
    supportTitle: "Contact support",
    legalTitle: "Content rights claim",
    legalLead:
      "Describe the material and the grounds for the claim. We reply to the address you leave.",
    supportLead:
      "Tell us what happened. We answer to the account email within a working day.",
    reason: "What happened",
    reasons: {
      broken: "It does not work",
      looks: "It looks different from the preview",
      agent: "The agent could not install it",
      other: "Something else",
    },
    subject: "Subject",
    message: "Details",
    messageHint: "At least 20 characters: what you did and what you got.",
    email: "Email for the reply",
    send: "Send",
    sending: "Sending…",
    sent: "We have your report",
    sentNote:
      "We will reply by email. The reference number goes to that address.",
    close: "Close",
    tooOften: "Too often. Try again in a few minutes.",
    failed: "Could not send. Please try again.",
    required: "Fill in the subject and the details.",
  },
} as const
